const std = @import("std");
const posix = std.posix;

// Generated from std/os/linux/errno/generic.zig
// https://github.com/ziglang/zig/blob/master/lib/std/os/linux/errno/generic.zig

pub const Error = error{
    OperationNotPermitted, // PERM = 1 Operation not permitted
    NoSuchFileOrDirectory, // NOENT = 2 No such file or directory
    NoSuchProcess, // SRCH = 3 No such process
    InterruptedSystemCall, // INTR = 4 Interrupted system call
    IOError, // IO = 5 I/O error
    NoSuchDeviceOrAddress, // NXIO = 6 No such device or address
    ArgListTooLong, // @"2BIG" = 7 Arg list too long
    ExecFormatError, // NOEXEC = 8 Exec format error
    BadFileNumber, // BADF = 9 Bad file number
    NoChildProcesses, // CHILD = 10 No child processes
    TryAgain, // AGAIN = 11 Try again
    OutOfMemory, // NOMEM = 12 Out of memory
    PermissionDenied, // ACCES = 13 Permission denied
    BadAddress, // FAULT = 14 Bad address
    BlockDeviceRequired, // NOTBLK = 15 Block device required
    DeviceOrResourceBusy, // BUSY = 16 Device or resource busy
    FileExists, // EXIST = 17 File exists
    CrossdeviceLink, // XDEV = 18 Cross-device link
    NoSuchDevice, // NODEV = 19 No such device
    NotADirectory, // NOTDIR = 20 Not a directory
    IsADirectory, // ISDIR = 21 Is a directory
    InvalidArgument, // INVAL = 22 Invalid argument
    FileTableOverflow, // NFILE = 23 File table overflow
    TooManyOpenFiles, // MFILE = 24 Too many open files
    NotATypewriter, // NOTTY = 25 Not a typewriter
    TextFileBusy, // TXTBSY = 26 Text file busy
    FileTooLarge, // FBIG = 27 File too large
    NoSpaceLeftOnDevice, // NOSPC = 28 No space left on device
    IllegalSeek, // SPIPE = 29 Illegal seek
    ReadonlyFileSystem, // ROFS = 30 Read-only file system
    TooManyLinks, // MLINK = 31 Too many links
    BrokenPipe, // PIPE = 32 Broken pipe
    MathArgumentOutOfDomainOfFunc, // DOM = 33 Math argument out of domain of func
    MathResultNotRepresentable, // RANGE = 34 Math result not representable
    ResourceDeadlockWouldOccur, // DEADLK = 35 Resource deadlock would occur
    FileNameTooLong, // NAMETOOLONG = 36 File name too long
    NoRecordLocksAvailable, // NOLCK = 37 No record locks available
    FunctionNotImplemented, // NOSYS = 38 Function not implemented
    DirectoryNotEmpty, // NOTEMPTY = 39 Directory not empty
    TooManySymbolicLinksEncountered, // LOOP = 40 Too many symbolic links encountered
    NoMessageOfDesiredType, // NOMSG = 42 No message of desired type
    IdentifierRemoved, // IDRM = 43 Identifier removed
    ChannelNumberOutOfRange, // CHRNG = 44 Channel number out of range
    Level2NotSynchronized, // L2NSYNC = 45 Level 2 not synchronized
    Level3Halted, // L3HLT = 46 Level 3 halted
    Level3Reset, // L3RST = 47 Level 3 reset
    LinkNumberOutOfRange, // LNRNG = 48 Link number out of range
    ProtocolDriverNotAttached, // UNATCH = 49 Protocol driver not attached
    NoCsiStructureAvailable, // NOCSI = 50 No CSI structure available
    Level2Halted, // L2HLT = 51 Level 2 halted
    InvalidExchange, // BADE = 52 Invalid exchange
    InvalidRequestDescriptor, // BADR = 53 Invalid request descriptor
    ExchangeFull, // XFULL = 54 Exchange full
    NoAnode, // NOANO = 55 No anode
    InvalidRequestCode, // BADRQC = 56 Invalid request code
    InvalidSlot, // BADSLT = 57 Invalid slot
    BadFontFileFormat, // BFONT = 59 Bad font file format
    DeviceNotAStream, // NOSTR = 60 Device not a stream
    NoDataAvailable, // NODATA = 61 No data available
    TimerExpired, // TIME = 62 Timer expired
    OutOfStreamsResources, // NOSR = 63 Out of streams resources
    MachineIsNotOnTheNetwork, // NONET = 64 Machine is not on the network
    PackageNotInstalled, // NOPKG = 65 Package not installed
    ObjectIsRemote, // REMOTE = 66 Object is remote
    LinkHasBeenSevered, // NOLINK = 67 Link has been severed
    AdvertiseError, // ADV = 68 Advertise error
    SrmountError, // SRMNT = 69 Srmount error
    CommunicationErrorOnSend, // COMM = 70 Communication error on send
    ProtocolError, // PROTO = 71 Protocol error
    MultihopAttempted, // MULTIHOP = 72 Multihop attempted
    RfsSpecificError, // DOTDOT = 73 RFS specific error
    NotADataMessage, // BADMSG = 74 Not a data message
    ValueTooLargeForDefinedDataType, // OVERFLOW = 75 Value too large for defined data type
    NameNotUniqueOnNetwork, // NOTUNIQ = 76 Name not unique on network
    FileDescriptorInBadState, // BADFD = 77 File descriptor in bad state
    RemoteAddressChanged, // REMCHG = 78 Remote address changed
    CanNotAccessANeededSharedLibrary, // LIBACC = 79 Can not access a needed shared library
    AccessingACorruptedSharedLibrary, // LIBBAD = 80 Accessing a corrupted shared library
    LibSectionInAoutCorrupted, // LIBSCN = 81 .lib section in a.out corrupted
    AttemptingToLinkInTooManySharedLibraries, // LIBMAX = 82 Attempting to link in too many shared libraries
    CannotExecASharedLibraryDirectly, // LIBEXEC = 83 Cannot exec a shared library directly
    IllegalByteSequence, // ILSEQ = 84 Illegal byte sequence
    InterruptedSystemCallShouldBeRestarted, // RESTART = 85 Interrupted system call should be restarted
    StreamsPipeError, // STRPIPE = 86 Streams pipe error
    TooManyUsers, // USERS = 87 Too many users
    SocketOperationOnNonsocket, // NOTSOCK = 88 Socket operation on non-socket
    DestinationAddressRequired, // DESTADDRREQ = 89 Destination address required
    MessageTooLong, // MSGSIZE = 90 Message too long
    ProtocolWrongTypeForSocket, // PROTOTYPE = 91 Protocol wrong type for socket
    ProtocolNotAvailable, // NOPROTOOPT = 92 Protocol not available
    ProtocolNotSupported, // PROTONOSUPPORT = 93 Protocol not supported
    SocketTypeNotSupported, // SOCKTNOSUPPORT = 94 Socket type not supported
    OperationNotSupportedOnTransportEndpoint, // OPNOTSUPP = 95 Operation not supported on transport endpoint
    ProtocolFamilyNotSupported, // PFNOSUPPORT = 96 Protocol family not supported
    AddressFamilyNotSupportedByProtocol, // AFNOSUPPORT = 97 Address family not supported by protocol
    AddressAlreadyInUse, // ADDRINUSE = 98 Address already in use
    CannotAssignRequestedAddress, // ADDRNOTAVAIL = 99 Cannot assign requested address
    NetworkIsDown, // NETDOWN = 100 Network is down
    NetworkIsUnreachable, // NETUNREACH = 101 Network is unreachable
    NetworkDroppedConnectionBecauseOfReset, // NETRESET = 102 Network dropped connection because of reset
    SoftwareCausedConnectionAbort, // CONNABORTED = 103 Software caused connection abort
    ConnectionResetByPeer, // CONNRESET = 104 Connection reset by peer
    NoBufferSpaceAvailable, // NOBUFS = 105 No buffer space available
    TransportEndpointIsAlreadyConnected, // ISCONN = 106 Transport endpoint is already connected
    TransportEndpointIsNotConnected, // NOTCONN = 107 Transport endpoint is not connected
    CannotSendAfterTransportEndpointShutdown, // SHUTDOWN = 108 Cannot send after transport endpoint shutdown
    TooManyReferences, // TOOMANYREFS = 109 Too many references: cannot splice
    ConnectionTimedOut, // TIMEDOUT = 110 Connection timed out
    ConnectionRefused, // CONNREFUSED = 111 Connection refused
    HostIsDown, // HOSTDOWN = 112 Host is down
    NoRouteToHost, // HOSTUNREACH = 113 No route to host
    OperationAlreadyInProgress, // ALREADY = 114 Operation already in progress
    OperationNowInProgress, // INPROGRESS = 115 Operation now in progress
    StaleNfsFileHandle, // STALE = 116 Stale NFS file handle
    StructureNeedsCleaning, // UCLEAN = 117 Structure needs cleaning
    NotAXenixNamedTypeFile, // NOTNAM = 118 Not a XENIX named type file
    NoXenixSemaphoresAvailable, // NAVAIL = 119 No XENIX semaphores available
    IsANamedTypeFile, // ISNAM = 120 Is a named type file
    RemoteIOError, // REMOTEIO = 121 Remote I/O error
    QuotaExceeded, // DQUOT = 122 Quota exceeded
    NoMediumFound, // NOMEDIUM = 123 No medium found
    WrongMediumType, // MEDIUMTYPE = 124 Wrong medium type
    OperationCanceled, // CANCELED = 125 Operation canceled
    RequiredKeyNotAvailable, // NOKEY = 126 Required key not available
    KeyHasExpired, // KEYEXPIRED = 127 Key has expired
    KeyHasBeenRevoked, // KEYREVOKED = 128 Key has been revoked
    KeyWasRejectedByService, // KEYREJECTED = 129 Key was rejected by service
    OwnerDied, // OWNERDEAD = 130 Owner died
    StateNotRecoverable, // NOTRECOVERABLE = 131 State not recoverable
    OperationNotPossibleDueToRfkill, // RFKILL = 132 Operation not possible due to RF-kill
    MemoryPageHasHardwareError, // HWPOISON = 133 Memory page has hardware error
    DnsServerReturnedAnswerWithNoData, // NSRNODATA = 160 DNS server returned answer with no data
    DnsServerClaimsQueryWasMisformatted, // NSRFORMERR = 161 DNS server claims query was misformatted
    DnsServerReturnedGeneralFailure, // NSRSERVFAIL = 162 DNS server returned general failure
    DomainNameNotFound, // NSRNOTFOUND = 163 Domain name not found
    DnsServerDoesNotImplementRequestedOperation, // NSRNOTIMP = 164 DNS server does not implement requested operation
    DnsServerRefusedQuery, // NSRREFUSED = 165 DNS server refused query
    MisformattedDnsQuery, // NSRBADQUERY = 166 Misformatted DNS query
    MisformattedDomainName, // NSRBADNAME = 167 Misformatted domain name
    UnsupportedAddressFamily, // NSRBADFAMILY = 168 Unsupported address family
    MisformattedDnsReply, // NSRBADRESP = 169 Misformatted DNS reply
    CouldNotContactDnsServers, // NSRCONNREFUSED = 170 Could not contact DNS servers
    TimeoutWhileContactingDnsServers, // NSRTIMEOUT = 171 Timeout while contacting DNS servers
    EndOfFile, // NSROF = 172 End of file
    ErrorReadingFile, // NSRFILE = 173 Error reading file
    DnsOutOfMemory, // NSRNOMEM = 174 Out of memory
    ApplicationTerminatedLookup, // NSRDESTRUCTION = 175 Application terminated lookup
    DnsDomainNameIsTooLong, // NSRQUERYDOMAINTOOLONG = 176 Domain name is too long
    DnsLoopDomainNameIsTooLong, // NSRCNAMELOOP = 177 Domain name is too long
} || posix.UnexpectedError;

pub fn toError(errno: posix.E) Error {
    return switch (errno) {
        .PERM => error.OperationNotPermitted, // 1 Operation not permitted
        .NOENT => error.NoSuchFileOrDirectory, // 2 No such file or directory
        .SRCH => error.NoSuchProcess, // 3 No such process
        .INTR => error.InterruptedSystemCall, // 4 Interrupted system call
        .IO => error.IOError, // 5 I/O error
        .NXIO => error.NoSuchDeviceOrAddress, // 6 No such device or address
        .@"2BIG" => error.ArgListTooLong, // 7 Arg list too long
        .NOEXEC => error.ExecFormatError, // 8 Exec format error
        .BADF => error.BadFileNumber, // 9 Bad file number
        .CHILD => error.NoChildProcesses, // 10 No child processes
        .AGAIN => error.TryAgain, // 11 Try again
        .NOMEM => error.OutOfMemory, // 12 Out of memory
        .ACCES => error.PermissionDenied, // 13 Permission denied
        .FAULT => error.BadAddress, // 14 Bad address
        .NOTBLK => error.BlockDeviceRequired, // 15 Block device required
        .BUSY => error.DeviceOrResourceBusy, // 16 Device or resource busy
        .EXIST => error.FileExists, // 17 File exists
        .XDEV => error.CrossdeviceLink, // 18 Cross-device link
        .NODEV => error.NoSuchDevice, // 19 No such device
        .NOTDIR => error.NotADirectory, // 20 Not a directory
        .ISDIR => error.IsADirectory, // 21 Is a directory
        .INVAL => error.InvalidArgument, // 22 Invalid argument
        .NFILE => error.FileTableOverflow, // 23 File table overflow
        .MFILE => error.TooManyOpenFiles, // 24 Too many open files
        .NOTTY => error.NotATypewriter, // 25 Not a typewriter
        .TXTBSY => error.TextFileBusy, // 26 Text file busy
        .FBIG => error.FileTooLarge, // 27 File too large
        .NOSPC => error.NoSpaceLeftOnDevice, // 28 No space left on device
        .SPIPE => error.IllegalSeek, // 29 Illegal seek
        .ROFS => error.ReadonlyFileSystem, // 30 Read-only file system
        .MLINK => error.TooManyLinks, // 31 Too many links
        .PIPE => error.BrokenPipe, // 32 Broken pipe
        .DOM => error.MathArgumentOutOfDomainOfFunc, // 33 Math argument out of domain of func
        .RANGE => error.MathResultNotRepresentable, // 34 Math result not representable
        .DEADLK => error.ResourceDeadlockWouldOccur, // 35 Resource deadlock would occur
        .NAMETOOLONG => error.FileNameTooLong, // 36 File name too long
        .NOLCK => error.NoRecordLocksAvailable, // 37 No record locks available
        .NOSYS => error.FunctionNotImplemented, // 38 Function not implemented
        .NOTEMPTY => error.DirectoryNotEmpty, // 39 Directory not empty
        .LOOP => error.TooManySymbolicLinksEncountered, // 40 Too many symbolic links encountered
        .NOMSG => error.NoMessageOfDesiredType, // 42 No message of desired type
        .IDRM => error.IdentifierRemoved, // 43 Identifier removed
        .CHRNG => error.ChannelNumberOutOfRange, // 44 Channel number out of range
        .L2NSYNC => error.Level2NotSynchronized, // 45 Level 2 not synchronized
        .L3HLT => error.Level3Halted, // 46 Level 3 halted
        .L3RST => error.Level3Reset, // 47 Level 3 reset
        .LNRNG => error.LinkNumberOutOfRange, // 48 Link number out of range
        .UNATCH => error.ProtocolDriverNotAttached, // 49 Protocol driver not attached
        .NOCSI => error.NoCsiStructureAvailable, // 50 No CSI structure available
        .L2HLT => error.Level2Halted, // 51 Level 2 halted
        .BADE => error.InvalidExchange, // 52 Invalid exchange
        .BADR => error.InvalidRequestDescriptor, // 53 Invalid request descriptor
        .XFULL => error.ExchangeFull, // 54 Exchange full
        .NOANO => error.NoAnode, // 55 No anode
        .BADRQC => error.InvalidRequestCode, // 56 Invalid request code
        .BADSLT => error.InvalidSlot, // 57 Invalid slot
        .BFONT => error.BadFontFileFormat, // 59 Bad font file format
        .NOSTR => error.DeviceNotAStream, // 60 Device not a stream
        .NODATA => error.NoDataAvailable, // 61 No data available
        .TIME => error.TimerExpired, // 62 Timer expired
        .NOSR => error.OutOfStreamsResources, // 63 Out of streams resources
        .NONET => error.MachineIsNotOnTheNetwork, // 64 Machine is not on the network
        .NOPKG => error.PackageNotInstalled, // 65 Package not installed
        .REMOTE => error.ObjectIsRemote, // 66 Object is remote
        .NOLINK => error.LinkHasBeenSevered, // 67 Link has been severed
        .ADV => error.AdvertiseError, // 68 Advertise error
        .SRMNT => error.SrmountError, // 69 Srmount error
        .COMM => error.CommunicationErrorOnSend, // 70 Communication error on send
        .PROTO => error.ProtocolError, // 71 Protocol error
        .MULTIHOP => error.MultihopAttempted, // 72 Multihop attempted
        .DOTDOT => error.RfsSpecificError, // 73 RFS specific error
        .BADMSG => error.NotADataMessage, // 74 Not a data message
        .OVERFLOW => error.ValueTooLargeForDefinedDataType, // 75 Value too large for defined data type
        .NOTUNIQ => error.NameNotUniqueOnNetwork, // 76 Name not unique on network
        .BADFD => error.FileDescriptorInBadState, // 77 File descriptor in bad state
        .REMCHG => error.RemoteAddressChanged, // 78 Remote address changed
        .LIBACC => error.CanNotAccessANeededSharedLibrary, // 79 Can not access a needed shared library
        .LIBBAD => error.AccessingACorruptedSharedLibrary, // 80 Accessing a corrupted shared library
        .LIBSCN => error.LibSectionInAoutCorrupted, // 81 .lib section in a.out corrupted
        .LIBMAX => error.AttemptingToLinkInTooManySharedLibraries, // 82 Attempting to link in too many shared libraries
        .LIBEXEC => error.CannotExecASharedLibraryDirectly, // 83 Cannot exec a shared library directly
        .ILSEQ => error.IllegalByteSequence, // 84 Illegal byte sequence
        .RESTART => error.InterruptedSystemCallShouldBeRestarted, // 85 Interrupted system call should be restarted
        .STRPIPE => error.StreamsPipeError, // 86 Streams pipe error
        .USERS => error.TooManyUsers, // 87 Too many users
        .NOTSOCK => error.SocketOperationOnNonsocket, // 88 Socket operation on non-socket
        .DESTADDRREQ => error.DestinationAddressRequired, // 89 Destination address required
        .MSGSIZE => error.MessageTooLong, // 90 Message too long
        .PROTOTYPE => error.ProtocolWrongTypeForSocket, // 91 Protocol wrong type for socket
        .NOPROTOOPT => error.ProtocolNotAvailable, // 92 Protocol not available
        .PROTONOSUPPORT => error.ProtocolNotSupported, // 93 Protocol not supported
        .SOCKTNOSUPPORT => error.SocketTypeNotSupported, // 94 Socket type not supported
        .OPNOTSUPP => error.OperationNotSupportedOnTransportEndpoint, // 95 Operation not supported on transport endpoint
        .PFNOSUPPORT => error.ProtocolFamilyNotSupported, // 96 Protocol family not supported
        .AFNOSUPPORT => error.AddressFamilyNotSupportedByProtocol, // 97 Address family not supported by protocol
        .ADDRINUSE => error.AddressAlreadyInUse, // 98 Address already in use
        .ADDRNOTAVAIL => error.CannotAssignRequestedAddress, // 99 Cannot assign requested address
        .NETDOWN => error.NetworkIsDown, // 100 Network is down
        .NETUNREACH => error.NetworkIsUnreachable, // 101 Network is unreachable
        .NETRESET => error.NetworkDroppedConnectionBecauseOfReset, // 102 Network dropped connection because of reset
        .CONNABORTED => error.SoftwareCausedConnectionAbort, // 103 Software caused connection abort
        .CONNRESET => error.ConnectionResetByPeer, // 104 Connection reset by peer
        .NOBUFS => error.NoBufferSpaceAvailable, // 105 No buffer space available
        .ISCONN => error.TransportEndpointIsAlreadyConnected, // 106 Transport endpoint is already connected
        .NOTCONN => error.TransportEndpointIsNotConnected, // 107 Transport endpoint is not connected
        .SHUTDOWN => error.CannotSendAfterTransportEndpointShutdown, // 108 Cannot send after transport endpoint shutdown
        .TOOMANYREFS => error.TooManyReferences, // 109 Too many references: cannot splice
        .TIMEDOUT => error.ConnectionTimedOut, // 110 Connection timed out
        .CONNREFUSED => error.ConnectionRefused, // 111 Connection refused
        .HOSTDOWN => error.HostIsDown, // 112 Host is down
        .HOSTUNREACH => error.NoRouteToHost, // 113 No route to host
        .ALREADY => error.OperationAlreadyInProgress, // 114 Operation already in progress
        .INPROGRESS => error.OperationNowInProgress, // 115 Operation now in progress
        .STALE => error.StaleNfsFileHandle, // 116 Stale NFS file handle
        .UCLEAN => error.StructureNeedsCleaning, // 117 Structure needs cleaning
        .NOTNAM => error.NotAXenixNamedTypeFile, // 118 Not a XENIX named type file
        .NAVAIL => error.NoXenixSemaphoresAvailable, // 119 No XENIX semaphores available
        .ISNAM => error.IsANamedTypeFile, // 120 Is a named type file
        .REMOTEIO => error.RemoteIOError, // 121 Remote I/O error
        .DQUOT => error.QuotaExceeded, // 122 Quota exceeded
        .NOMEDIUM => error.NoMediumFound, // 123 No medium found
        .MEDIUMTYPE => error.WrongMediumType, // 124 Wrong medium type
        .CANCELED => error.OperationCanceled, // 125 Operation canceled
        .NOKEY => error.RequiredKeyNotAvailable, // 126 Required key not available
        .KEYEXPIRED => error.KeyHasExpired, // 127 Key has expired
        .KEYREVOKED => error.KeyHasBeenRevoked, // 128 Key has been revoked
        .KEYREJECTED => error.KeyWasRejectedByService, // 129 Key was rejected by service
        .OWNERDEAD => error.OwnerDied, // 130 Owner died
        .NOTRECOVERABLE => error.StateNotRecoverable, // 131 State not recoverable
        .RFKILL => error.OperationNotPossibleDueToRfkill, // 132 Operation not possible due to RF-kill
        .HWPOISON => error.MemoryPageHasHardwareError, // 133 Memory page has hardware error
        .NSRNODATA => error.DnsServerReturnedAnswerWithNoData, // 160 DNS server returned answer with no data
        .NSRFORMERR => error.DnsServerClaimsQueryWasMisformatted, // 161 DNS server claims query was misformatted
        .NSRSERVFAIL => error.DnsServerReturnedGeneralFailure, // 162 DNS server returned general failure
        .NSRNOTFOUND => error.DomainNameNotFound, // 163 Domain name not found
        .NSRNOTIMP => error.DnsServerDoesNotImplementRequestedOperation, // 164 DNS server does not implement requested operation
        .NSRREFUSED => error.DnsServerRefusedQuery, // 165 DNS server refused query
        .NSRBADQUERY => error.MisformattedDnsQuery, // 166 Misformatted DNS query
        .NSRBADNAME => error.MisformattedDomainName, // 167 Misformatted domain name
        .NSRBADFAMILY => error.UnsupportedAddressFamily, // 168 Unsupported address family
        .NSRBADRESP => error.MisformattedDnsReply, // 169 Misformatted DNS reply
        .NSRCONNREFUSED => error.CouldNotContactDnsServers, // 170 Could not contact DNS servers
        .NSRTIMEOUT => error.TimeoutWhileContactingDnsServers, // 171 Timeout while contacting DNS servers
        .NSROF => error.EndOfFile, // 172 End of file
        .NSRFILE => error.ErrorReadingFile, // 173 Error reading file
        .NSRNOMEM => error.DnsOutOfMemory, // 174 Out of memory
        .NSRDESTRUCTION => error.ApplicationTerminatedLookup, // 175 Application terminated lookup
        .NSRQUERYDOMAINTOOLONG => error.DnsDomainNameIsTooLong, // 176 Domain name is too long
        .NSRCNAMELOOP => error.DnsLoopDomainNameIsTooLong, // 177 Domain name is too long
        else => |e| return posix.unexpectedErrno(e),
    };
}

pub inline fn name(errno: posix.E) []const u8 {
    return @errorName(toError(errno));
}

const testing = std.testing;

test "errnoError" {
    try testing.expect(Error.OperationNotPermitted == toError(.PERM));
}
