name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ianic/iox
          path: './iox'
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build
      - run: zig build test --summary all
      - run: zig test -lc --dep iox -Mroot=src/main.zig    -Miox=iox/src/root.zig
      - run: zig run  -lc --dep iox -Mroot=src/Options.zig -Miox=iox/src/root.zig -- --max-mem 1G
