name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build
      - run: zig build test
      - run: zig test -lc src/main.zig
      - run: zig run -lc src/Options.zig -- --max-mem 1G
